---
title: "Final Project - Prep"
author: "Pieter Quinton"
date: "12/3/2019"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, results = 'asis')
```

```{r libraries}

# Load in the libraries needed for data cleaning

library(gifski)
library(gganimate)
library(fs)
library(sf)
library(janitor)
library(tidyverse)
library(stargazer)
```

```{r Nation}

# Main data for the first tab in the shiny app.
# Added rowname column to provide an inverse population ranked column.
# Re-arranged the dataset so it would be in the order I want for the pickerInput in shiny.

zillow_data_cities <- read.csv("data/Metro_Zhvi_SingleFamilyResidence.csv") %>%
  clean_names() %>%
  filter(region_name != "United States") %>%
  arrange(desc(size_rank)) %>%
  rownames_to_column(var = "rowname") %>%
  arrange(size_rank) %>%
  select(rowname, region_name, size_rank, x2019_08) %>%
  gather(date, price, 4) %>%
  mutate(date = str_remove(date, "x")) %>%
  mutate(date = str_replace(date, "_", "-")) %>%
  mutate(Rank = size_rank,
         Price = price)

# Wrote the cleaned data in to the shiny app.

write_csv(zillow_data_cities, "Final-Project/cities.csv")
```

```{r Oregon model}

# median home price data

zillow_data_counties <- read_csv("data/County_Zhvi_SingleFamilyResidence.csv",
                                 col_types = cols(
                                 .default = col_double(),
                                 RegionName = col_character(),
                                 State = col_character(),
                                 Metro = col_character(),
                                 StateCodeFIPS = col_character(),
                                 MunicipalCodeFIPS = col_character()
                                ))

zillowOR <- zillow_data_counties %>%
  filter(State == "OR") %>%
  select(-(`1996-04`:`2000-12`)) %>%
  gather(date, median, 8:233) %>%
  mutate(year = as.POSIXct(paste(date,"-01",sep=""))) %>%
  mutate(year = format(year, "%Y")) %>%
  group_by(MunicipalCodeFIPS, year) %>%
  summarize(avg = mean(median)) %>%
  ungroup(MunicipalCodeFIPS, year) %>%
  group_by(MunicipalCodeFIPS) %>%
  arrange(year) %>%
  mutate(diff = avg - lag(avg, default = first(avg))) %>%
  mutate(id = MunicipalCodeFIPS) %>%
  ungroup(MunicipalCodeFIPS) %>%
  select(id, year, avg, diff) %>%
  filter(id %in% c("005", "009", "051", "067", "071"))

# Permits data set

permitsMetro <- read_csv("data/BuildingPermitsPortlandMetro.csv", 
                         col_types = cols(
                         Location = col_character(),
                         Year = col_double(),
                         Series = col_character(),
                         `Series Code` = col_double(),
                         Month = col_double(),
                         Permits = col_double()
                        )) %>%
  select(-Month, -`Series Code`) %>%
  group_by(Location, Year) %>%
  summarize(total = sum(Permits)) %>%
  spread(Year, total) %>%
  arrange(Location) %>%
  ungroup(Location, Year) %>%
  gather(year, total, 2:20) %>%
  mutate(name = paste(Location, "Oregon", sep = ", ")) %>%
  select(-Location)

# Population data
# 2010-2018

oregon_county_pop <- read_csv("data/oregon_county_pop.csv", col_types = cols(
  GEO.id = col_character(),
  GEO.id2 = col_double(),
  `GEO.display-label` = col_character(),
  rescen42010 = col_double(),
  resbase42010 = col_double(),
  respop72010 = col_double(),
  respop72011 = col_double(),
  respop72012 = col_double(),
  respop72013 = col_double(),
  respop72014 = col_double(),
  respop72015 = col_double(),
  respop72016 = col_double(),
  respop72017 = col_double(),
  respop72018 = col_double()
)) %>%
  select(-GEO.id, -rescen42010, -resbase42010) 

# Rename columns

names(oregon_county_pop) <- c("id", "name", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018")

# 2000 - 2009

oregon_county_pop_2000 <- read_csv("data/counties_2000_2009.csv", col_types = cols(
  .default = col_double(),
  STNAME = col_character(),
  CTYNAME = col_character()
)) %>%
  clean_names() %>%
  filter(stname == "Oregon" & str_detect(ctyname, "County")) %>%
  mutate(name = paste(ctyname, "Oregon", sep = ", ")) %>%
  select(-ctyname, -sumlev, -region, -division, -state, -county, -stname, -estimatesbase2000, -census2010pop, -popestimate2010)

# Rename columns

names(oregon_county_pop_2000) <- c("2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "name")

# Merge population datasets

oregon_county_pop <- oregon_county_pop %>%
  merge(oregon_county_pop_2000, by = "name")

# For some reason it wasn't working to have it all as one piped function so I separated them out

oregon_county_pop <- oregon_county_pop %>%
  gather(year, pop, 3:21)

counties <- oregon_county_pop %>%
  mutate(id = str_remove(as.character(id), "41")) %>%
  filter(id %in% c("005", "009", "051", "067", "071")) %>%
  merge(permitsMetro, by = c("name", "year")) %>%
  merge(zillowOR, by = c("id", "year")) %>%
  arrange(year)

write_csv(counties, "Final-Project/counties.csv")  
```

```{r Portland}

# Data from Zillow broken down by neighborhood.
# Filtered to just get neighborhoods in Portland, OR
# Gathered the data to change it from wide data to long data.
# Now, each observation is its own row.
# Mutated the date column to change it from character to datetime. Had to add a generic day (1) to each month to make that mutation.

zillow_data_neighborhoods <- read_csv("data/Neighborhood_Zhvi_AllHomes.csv", col_types = cols(
  .default = col_double(),
  RegionName = col_character(),
  City = col_character(),
  State = col_character(),
  Metro = col_character(),
  CountyName = col_character()
)) %>%
  filter(City == "Portland" & State == "OR") %>%
  distinct() %>%
  gather(date, median, 8:289) %>%
  mutate(date = as.POSIXct(paste(date,"-01",sep=""))) %>%
  select(RegionName, date, median)

# Wrote the cleaned data to the shiny folder.

write_csv(zillow_data_neighborhoods, "Final-Project/neighborhoods.csv")
```


```{r Portland animated}
animatedPlot <- zillow_data_neighborhoods %>%
       group_by(RegionName) %>%
       ggplot(aes(x = date, y = median, group = RegionName, color = RegionName)) +
         geom_point() +
         theme(
           legend.position = "none"
         ) +
         scale_y_continuous(lim = c(100000, 900000)) +
         labs(title = "Changes in Median House Price over Time Subsetted by Neighborhoods in Portland, OR",
              subtitle = "April, 1996 to August, 2019",
              y = "Median House Price ($)",
              x = "Date",
              caption = "As the plot shows, house prices have generally been increasing. \nHowever, there was a decline following the bursting of the housing market bubble around 2008 with prices bottoming out around 2012. \nThis trend occurred across all neighborhoods. \nSource: Zillow") +
         theme(
          plot.caption = element_text(hjust = 0)
         ) +
         transition_time(date)

write_rds(animatedPlot, "Final-Project/animated_map.rds")
```

